#!/bin/bash

Q=( 30 28 26 24 22 20 18 16 14 12 10 8 6 4 2 0 )
Qu=( 10 20 30 40 50 60 70 80 90 93 96 )
BPP=( 0.02 0.03 0.05 0.07 0.1 0.14 0.2 0.3 0.5 0.7 1 1.4 2 3 )

OUT_IMAGE="test.pgm"

for IN_IMAGE in *.pgm ; do

	OUT_FILE="test.dwi"
	BENCH_FILE="${IN_IMAGE%.pgm}.dwic.dat"
	echo "# Image : $IN_IMAGE" > $BENCH_FILE
	for q in ${Q[@]} ; do
		dwic -i $IN_IMAGE -o $OUT_FILE -q $q -v 0
		tmp=( `ls -l $OUT_FILE` )
		file_size=${tmp[4]}
		dwic -i $OUT_FILE -o $OUT_IMAGE
		tmp=( `pnmpsnr $IN_IMAGE $OUT_IMAGE 2>&1 ` )
		psnr=${tmp[((${#tmp[@]}-2))]}
		echo "$file_size	$psnr" >> $BENCH_FILE
	done
	rm $OUT_FILE $OUT_IMAGE
	
# 	OUT_FILE="test.yaw"
# 	BENCH_FILE="${IN_IMAGE%.pgm}.yaw.dat"
# 	echo "# Image : $IN_IMAGE" > $BENCH_FILE
# 	for q in ${BPP[@]} ; do
# 		./yawica -E -t 9/7 -l 5 -p $q $IN_IMAGE $OUT_FILE
# 		tmp=( `ls -l $OUT_FILE` )
# 		file_size=${tmp[4]}
# 		./yawica -D $OUT_FILE $OUT_IMAGE
# 		tmp=( `pnmpsnr $IN_IMAGE $OUT_IMAGE 2>&1 ` )
# 		psnr=${tmp[((${#tmp[@]}-2))]}
# 		echo "$file_size	$psnr" >> $BENCH_FILE
# 	done
# 	rm $OUT_FILE $OUT_IMAGE
# 	
# 	OUT_FILE="test.jpg"
# 	BENCH_FILE="${IN_IMAGE%.png}.jpeg.dat"
# 	echo "# Image : $IN_IMAGE" > $BENCH_FILE
# 	for q in ${Qu[@]} ; do
# 		convert $IN_IMAGE -quality $q $OUT_FILE
# 		tmp=( `ls -l $OUT_FILE` )
# 		file_size=${tmp[4]}
# 		convert $OUT_FILE $OUT_IMAGE
# 		tmp=( `compare -metric PSNR $IN_IMAGE $OUT_IMAGE /dev/null | grep dB` )
# 		psnr=${tmp[0]}
# 		echo "$file_size	$psnr" >> $BENCH_FILE
# 	done
# 	rm $OUT_FILE $OUT_IMAGE
# 	
# 	OUT_FILE="test.jp2"
# 	BENCH_FILE="${IN_IMAGE%.pgm}.jp2k.dat"
# 	echo "# Image : $IN_IMAGE" > $BENCH_FILE
# 	for q in ${Qu[@]} ; do
# 		convert $IN_IMAGE -quality $q $OUT_FILE
# 		tmp=( `ls -l $OUT_FILE` )
# 		file_size=${tmp[4]}
# 		convert $OUT_FILE $OUT_IMAGE
# 		tmp=( `pnmpsnr $IN_IMAGE $OUT_IMAGE 2>&1 ` )
# 		psnr=${tmp[((${#tmp[@]}-2))]}
# 		echo "$file_size	$psnr" >> $BENCH_FILE
# 	done
# 	rm $OUT_FILE $OUT_IMAGE
done
